name: Export arc.json

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run arc-export
        run : |
          docker pull ghcr.io/nfdi4plants/arc-export:main  
          docker run -v $(pwd):/arc ghcr.io/nfdi4plants/arc-export:main /arc-export -p arc
      - name: Read Results
        uses: actions/upload-artifact@v4
        with:
          name: arc-isa.json
          path: | 
            arc-isa.json

      